exercise_task:
  description: >    
    Each bullet point start with a exercise, and then followed with a reason why it is relevant to the patient.
    
    Patient profile:
    {patient_profile}

    Diagnosis:
    {diagnosis}

    Based on given patients profile and diagnosis, provide expert advice on exercise for optimal health and longevity.
    Please mention the type of exercise, intensity, duration, and frequency.
    Start answer with "Here are some exercise recommendations for you:"
  expected_output: >
    A list with maximum 5 bullet points of the most relevant information about exercise for optimal health and longevity. 
    Formatted as markdown without '```'. 
  agent: exercise_expert