writer_task:
  description: >    
    take inputs and write a nice {output_file_format} file with the inputs given.
    
    Patient profile:
    {patient_profile}

    Diagnosis:
    {diagnosis}

    Supplements recommendation:
    {supplements_recommendation}

    Exercise recommendation:
    {exercise_recommendation}

    Based on given patients profile, and recommendations of different categories provided by other AI longevity GP. 
    Write a nice {output_file_format} file that format the given .md file nicely.

    If there are references mentioned, please add a nice reference list at the end of the html file, and maintain nicely the intext citations. Follow AMA style.
  expected_output: >
    A nice {output_file_format} file with the inputs given. 
    Formatted as markdown without '```'. 

  agent: writer_expert